pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.0.10'
    }
}
rootProject.name = 'OsmTools'

include ':osmToolsBasic'
include ':osmToolsCore'
include ':osmToolsDataWriter'
include ':osmToolsPbfWriter'
include 'maptiler-api'
include 'osmToolsElevation'
include 'osmToolsPmtiles'


// Composite build - mapsforge-tiler
def localMapsforgeTiler = file('../mapsforgeTiler')
if (localMapsforgeTiler.exists()) {
    println(">> [LOCAL] mapsforge-tiler")
    includeBuild('../mapsforgeTiler')
} else {
    println(">> [PUBLISHED] mapsforge-tiler")
}