/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param token 
 * @param description 
 * @param userAgent 
 * @param origins 
 * @param created 
 * @param changed 
 */
@Serializable

data class APIKey (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "token")
    val token: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "user_agent")
    val userAgent: kotlin.String? = null,

    @SerialName(value = "origins")
    val origins: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "created")
    val created: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "changed")
    val changed: java.time.OffsetDateTime? = null

)

