/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param userAgent 
 * @param origins 
 */
@Serializable

data class APIKeySettings (

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "user_agent")
    val userAgent: kotlin.String? = null,

    @SerialName(value = "origins")
    val origins: kotlin.collections.List<kotlin.String>? = null

)

