/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param label 
 * @param description 
 */
@Serializable

data class Legend (

    @SerialName(value = "item_id")
    val itemId: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?

)

