/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param description 
 * @param attribution 
 */
@Serializable

data class TilesetMetadataChange (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "attribution")
    val attribution: kotlin.String

)

