/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model

import com.asamm.locus.client.model.Tileset

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cursor 
 * @param items 
 */
@Serializable

data class TilesetPage (

    @SerialName(value = "cursor")
    val cursor: kotlin.ByteArray? = null,

    @SerialName(value = "items")
    val items: kotlin.collections.List<Tileset>? = null

)

