/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param filename 
 * @param propertySize size in bytes
 */
@Serializable

data class TilesetIngestCreate (

    @SerialName(value = "filename")
    val filename: kotlin.String,

    /* size in bytes */
    @SerialName(value = "size")
    val propertySize: kotlin.Long

)

