/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.UseSerializers

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param attribution 
 */

@Serializable

data class Tileset (

    @Serializable(with = UUIDSerializer::class) @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "attribution")
    val attribution: kotlin.String? = null

)

