/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param date 
 * @param `value` 
 */
@Serializable

data class TimelineData (

    @Contextual @SerialName(value = "date")
    val date: java.time.LocalDate,

    @SerialName(value = "value")
    val `value`: kotlin.Int

)

