/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model

import com.asamm.locus.client.model.TimelineData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param groupId 
 * @param itemId 
 * @param `data` 
 * @param estimatedData 
 */
@Serializable

data class TimelineDataset (

    @SerialName(value = "group_id")
    val groupId: TimelineDataset.GroupId,

    @SerialName(value = "item_id")
    val itemId: kotlin.String,

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<TimelineData>,

    @SerialName(value = "estimated_data")
    val estimatedData: TimelineData? = null

) {

    /**
     * 
     *
     * Values: request,export,session
     */
    @Serializable
    enum class GroupId(val value: kotlin.String) {
        @SerialName(value = "request") request("request"),
        @SerialName(value = "export") export("export"),
        @SerialName(value = "session") session("session");
    }
}

