/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model

import com.asamm.locus.client.model.TopData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param groupId 
 * @param `data` 
 */
@Serializable

data class TopDataset (

    @SerialName(value = "group_id")
    val groupId: TopDataset.GroupId,

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<TopData>

) {

    /**
     * 
     *
     * Values: request,export,session
     */
    @Serializable
    enum class GroupId(val value: kotlin.String) {
        @SerialName(value = "request") request("request"),
        @SerialName(value = "export") export("export"),
        @SerialName(value = "session") session("session");
    }
}

