/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.asamm.locus.client.model

import com.asamm.locus.client.model.Legend
import com.asamm.locus.client.model.TopDataset

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param since 
 * @param until 
 * @param datasets 
 * @param legend 
 */
@Serializable

data class TopResponseJSON (

    @Contextual @SerialName(value = "since")
    val since: java.time.LocalDate,

    @Contextual @SerialName(value = "until")
    val until: java.time.LocalDate,

    @SerialName(value = "datasets")
    val datasets: kotlin.collections.List<TopDataset>,

    @SerialName(value = "legend")
    val legend: kotlin.collections.List<Legend>

)

